const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const SET_BREED = "SET_BREED";
const SET_BREEDS = "SET_BREEDS";
const SET_CATS_IMAGES = "SET_CATS_IMAGES";
const LOADING = "LOADING";

export {
    LOGIN_USER,
    LOGOUT_USER,
    SET_BREEDS,
    SET_BREED,
    SET_CATS_IMAGES,
    LOADING
};
