const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const SET_BREEDS = "SET_BREEDS";
const SET_CATS_IMAGES = "SET_CATS_IMAGES";

export { LOGIN_USER, LOGOUT_USER, SET_BREEDS, SET_CATS_IMAGES };
